#include <iostream>
#include <cstdlib>
#include <ctime>
#include "athlete.h"
using namespace std;

extern string cg;         // Terminal colour code (gold)
extern string cb;        	// Terminal colour code (blue)
extern string cr;         // Terminal colour code (red)
extern string c0;      		// Reset Terminal colour

// List of possible first names and surnames
string gNames[100] = {"Emma","Olivia","Ava","Isabella","Sophia","Mia","Charlotte","Amelia","Evelyn","Abigail","Harper","Emily","Elizabeth","Avery","Sofia","Ella","Madison","Scarlett","Victoria","Aria","Grace","Chloe","Camila","Penelope","Riley","Layla","Lillian","Nora","Zoey","Mila","Aubrey","Hannah","Lily","Addison","Eleanor","Natalie","Luna","Savannah","Brooklyn","Leah","Zoe","Stella","Hazel","Ellie","Paisley","Audrey","Skylar","Violet","Claire","Bella","Aurora","Lucy","Anna","Samantha","Caroline","Genesis","Aaliyah","Kennedy","Kinsley","Allison","Maya","Sarah","Madelyn","Adeline","Alexa","Ariana","Elena","Gabriella","Naomi","Alice","Sadie","Hailey","Eva","Emilia","Autumn","Quinn","Nevaeh","Piper","Ruby","Serenity","Willow","Everly","Cora","Kaylee","Lydia","Aubree","Arianna","Eliana","Peyton","Melanie","Gianna","Isabelle","Julia","Valentina","Nova","Clara","Vivian","Reagan","Mackenzie","Madeline"};
string bNames[100] = {"Liam","Noah","William","James","Logan","Benjamin","Mason","Elijah","Oliver","Jacob","Lucas","Michael","Alexander","Ethan","Daniel","Matthew","Aiden","Henry","Joseph","Jackson","Samuel","Sebastian","David","Carter","Wyatt","Jayden","John","Owen","Dylan","Luke","Gabriel","Anthony","Isaac","Grayson","Jack","Julian","Levi","Christopher","Joshua","Andrew","Lincoln","Mateo","Ryan","Jaxon","Nathan","Aaron","Isaiah","Thomas","Charles","Caleb","Josiah","Christian","Hunter","Eli","Jonathan","Connor","Landon","Adrian","Asher","Cameron","Leo","Theodore","Jeremiah","Hudson","Robert","Easton","Nolan","Nicholas","Ezra","Colton","Angel","Brayden","Jordan","Dominic","Austin","Ian","Adam","Elias","Jaxson","Greyson","Jose","Ezekiel","Carson","Evan","Maverick","Bryson","Jace","Cooper","Xavier","Parker","Roman","Jason","Santiago","Chase","Sawyer","Gavin","Leonardo","Kayden","Ayden","Jameson"};
string sNames[100] = {"Jones","Brown","Williams","Johnson","White","Wilson","Lee","Taylor","Green","Thomas","Jackson","Thompson","Anderson","Roberts","Harris","Davis","James","Martin","Clark","King","Richards","Kelly","McDonald","Robinson","Miller","Robertson","Harrison","Nguyen","Edwards","Adams","Hill","Evans","Davies","Walker","Richardson","Lewis","Stevens","Parker","Carter","Cooper","Murphy","Baker","Clarke","Morris","Gray","Hall","Ryan","Watson","Campbell","Phillips","Moore","Young","Allen","Wood","Mitchell","Stewart","Scott","Hughes","Wright","Cook","Johnston","Matthews","Turner","Bell","Simpson","Graham","Thomson","Rogers","Murray","Kennedy","Morgan","O'Brien","Ross","Mills","Price","Fisher","Knight","Cox","Ellis","Reid","Bennett","Ward","Bailey","Butler","Mason","Marshall","Walsh","Russell","Webb","Cameron","Harvey","Shaw","Gibson","Chapman","Elliott","Hamilton","Tran","Pearce","Colling","Douglas-Hill"};

// Default athlete constructor
athlete::athlete() {	
  srand(time(0));  // Initialize random number generator.
  string aGender;


  // User decides if athlete is male or female.
  while (1) {

    cout << "Enter your gender (M/F): ";
    cin >> aGender;
    cout << endl;

	  if (aGender == "m" || aGender == "M") {
		  Gender = 1;
		  break;
	  } else if (aGender == "f" || aGender == "F") {
		  Gender = 0;
		  break;
	  } else {
		  cout << cr << "Error" << c0 << ": enter M or F.\n\n";
	  }

  }

  // Full name generated by program depending on gender chosen.
  string aName;

  if (Gender == 1) aName += bNames[rand() % 100]; 
  else	aName += gNames[rand() % 100]; 
  
  aName += " " + sNames[rand() % 100];

  // Prints name at end in blue
  cout << "Ok! Your name is: " << cb << aName << cr;
  cout << "\n\n";

  Name = aName;
}

// returns name of athlete
string athlete::getName() {
	return Name;
}

// returns gender of athlete
string athlete::getGender() {
	if (Gender == 1) {
		return "Male";
	} else {
		return "Female";
	}
}


// train function (only used by trainers)
void athlete::train(athlete * tAthlete) {

}

// athlete destructor
athlete::~athlete() {

}